### ISSUE TITLE
add user type

### ISSUE THREAD

**Issue by yujinjcho** [yujinjcho/rcruitme#16]
From https://github.com/yujinjcho/rcruitme/pull/12

candidate or recruiter. Wonder if a user could potentially be both? maybe just allow 1 for now.

**Comment by achiu8** [comment]
Hmm where in the signup flow do you think we should ask for this? If signing up for local account, can just put it on signup page, but what happens if they sign in with google? We could still automatically create the user, but with a null type, and redirect them to a separate page to select as long as it's null.

**Comment by yujinjcho** [comment]
yeah that sounds good
